name: ci

on:
  push:
    branches:
      - "main"
#  schedule:
#    # Run every Saturday at 7 PM
#    - cron: '0 19 * * 6'
env:
  TEST_TAG: khalouda11/appsilon-hello-r:test
  LATEST_TAG: khalouda11/appsilon-hello-r:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: ${{ env.TEST_TAG }}
      - name: Run container for testing
        run: |
          docker run -d --name myapp -p 3838:3838 ${{ env.TEST_TAG }}

      - name: Wait for container to be ready
        run: |
          sleep 10  # Adjust the sleep time as necessary

      - name: Test HTTP request
        run: |
          curl -f http://localhost:3838
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.LATEST_TAG }}